### PR TITLE
APEX-81 - Fix netlet snapshot dependency. Enforce no dependencies on snapshot versions in release builds.

### PR DESCRIPTION
**Pull request by vrozov**
@243826 Please merge after netlet 1.2 is released to maven central repository.

### CODE REVIEW

**Comment by 243826** [comment]
will there be a similar request for devel-3?

**Comment by vrozov** [comment]
Yes, please merge #38

**Comment by tweise** [comment]
Normally the pull request closes after you merge, Why is it not the case here?

**Comment by vrozov** [comment]
It looks that commit to apache git [46a84d01137b97ba4d7e25013aa0f36e3248f61e] (https://git1-us-west.apache.org/repos/asf/incubator-apex-core/repo?p=incubator-apex-core.git;a=commit;h=46a84d01137b97ba4d7e25013aa0f36e3248f61e) is different from pull request commit [ce32fb9d687e14b96a0c49b8a22d2c8902db6a49] (https://github.com/vrozov/incubator-apex-core/commit/ce32fb9d687e14b96a0c49b8a22d2c8902db6a49) causing pull request to stay open.

**Pull request closed without merging**
