### PR TITLE
Bumped minimum maven version to 3.0.5. Split enforcer executions by enforced rule.

### PR DESCRIPTION
**Pull request by vrozov**
@243826 Do we need the same changes in release-3.1?

### CODE REVIEW

**Comment by tweise** [comment]
Not needed in the release-3.1 branch.

**Comment by 243826** [comment]
Does this mean this change is already made in release-3.1 branch? If not, then please keep things consistent across branches. These branches are going to exist for a few months if not years.

**Comment by vrozov** [comment]
+1 to have this merged into release-3.1 branch. The change is not in release-3.1 branch. There is different workaround in the apex project pom.xml in release-3.1.

**Comment by tweise** [comment]
As far as process goes, the bar to put changes into the release branches is high because stability outweighs other considerations. We want to fix those issues that are important for patches. In the past, seemingly harmless changes later showed undesirable side effects. For example, the release-3.0 branch does not build with Maven 3.0.5 due to the semver plugin version. So I would rather reserve such changes for the devel branch, where they can sink in.

If you feel strongly about merging this particular change, fine by me. I have looked at it and don't foresee any issues.

**Comment by vrozov** [comment]
There are known issues with maven version 3.0 - 3.0.3. Please see comments for maven own project pom.xml (http://svn.apache.org/viewvc/maven/pom/trunk/maven/pom.xml?view=markup).

I suggest to wait till 3.1.1 release is out and merge the change into release-3.1 branch, so we avoid the last minute rush, but have the changes in for 3.1.2.

**Comment by 243826** [comment]
Let's do it after the release is out. Thanks.

--
Chetan

**Pull request merged**
