### PR TITLE
APEX-131: Setup Travis CI for continuous integration

### PR DESCRIPTION
**Pull request by brennonyork**
* added `.travis.yml` file to trigger the build
* integrated slack notifications

### CODE REVIEW

**Comment by tweise** [comment]
Brennon, can you add some more info regarding the slack notification to APEX-131. How does it work, how do I subscribe to it?

**Comment by brennonyork** [comment]
@tweise I added JIRAs to cover the slack info in more detail [here](https://malhar.atlassian.net/browse/APEX-133). Let me know if that doesn't make sense. Also, the build is passing now in Travis, but not sure what we should consider as the 'official' review process to commit code back (assuming if I wrote the patch I shouldn't merge it into the upstream repo). Thoughts? We can raise this on the dev list too.

**Comment by tweise** [comment]
Thanks, will pull it in.

**Comment by tweise** [comment]
As far as general review process, high level items on the JIRA and code detail iterations over pull requests. Also trying to keep the noise down by combining very detailed commits prior to submission, similar to what you would do when you submit a patch (make it a single change).

**Comment by tweise** [comment]
Brennon, I combined the commits into a single one as described and pushed the change. Hence this pull request needs to be closed manually.

**Comment by tweise** [comment]
One more thing: Please add your apache.org email address to your github profile.

**Comment by brennonyork** [comment]
@tweise 
1. are you saying you rebased the commits before you merged? (i.e. "I combined the commits into a single one as described and pushed the change"). Just trying to understand what exactly you did.
2. why do i need to update my github profile with my apache.org email? I currently have it setup such that, when I push commits into the apache master, it uses my @apache.org email, but for all personal work (i.e. PR's into Apex, Spark, etc.) I use my personal email. As for what email shows on my public github profile its my @capitalone.com address because that's what the company would like so that I represent them while I commit to various OSS. So, am I missing something here that I've screwed up or am I misunderstanding something? Let me know!

**Comment by tweise** [comment]
Thanks for creating the JIRA: https://malhar.atlassian.net/browse/APEX-137

We should have this discussion on dev@ and capture important points in the JIRA.

1. You can use rebase or squash to combine the commits, when all changes are made by a single user and I want a single commit then merge --squash works well.

2. No need to change your primary email address, add any additional addresses to your profile so that your commits are linked to your github username. Otherwise they show with gray icon for unknown user as seen in https://github.com/apache/incubator-apex-core/commit/e482804a856f2a5c8e3591af14cf552093017fe4

**Pull request closed without merging**
